apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: ghcr.io/2022-4400-exp/4420-go-helloworld-2:9cc7eab33a3f3142811c1a56ab20241d34351d87@sha256:4d3f21310b67a6bfe540787411ded747a4d2107bf8edd660852921b54c1f9823
        name: go-helloworld-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-helloworld-2
  type: NodePort
