name: "Build"
on:
  push:
    paths-ignore:
       - "manifest/**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build Docker image and publish
        run: |
          docker buildx build --push --platform linux/arm/v7,linux/amd64,linux/arm64,linux/s390x,linux/arm/v6 -t ghcr.io/2022-4400-exp/4420-go-helloworld-2:${{ github.sha }} .

      - name: Update manifest image tag
        id: update-image-tag
        continue-on-error: true
        run: |
          yq eval '.spec.template.spec.containers[0].image = "ghcr.io/2022-4400-exp/4420-go-helloworld-2:"+env(GITHUB_SHA' -i ./manifest/deployment.yaml
          git diff --name-only --exit-code

      - name: Commit&Push manifest
        if: steps.update-image-tag.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m "Update image tag to $GITHUB_SHA"
          git push
