name: "Build"
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Build Docker image and publish
        run: |
          docker buildx buld --push --platform linux/arm/v7,linux/amd64 -t ghcr.io/2022-4400-exp/4420-go-helloworld-2:${{ github.sha }} .
